apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp-postgresql
      protocol: TCP
      name: tcp-postgresql
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
