apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: tcp-redis
      protocol: TCP
      name: tcp-redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
