apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.services.user.replicas }}
  selector:
    matchLabels:
      {{- include "user-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.services.user.image }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.global.services.user.port }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:postgres_password@postgres:5432/userdb"
            - name: DATABASE_URL_SYNC
              value: "postgresql://postgres:postgres_password@postgres:5432/userdb"
            - name: JWT_SECRET
              value: {{ .Values.global.env.JWT_SECRET }}
            - name: JWT_ALGORITHM
              value: "HS256"
            - name: JWT_EXPIRY_MINUTES
              value: "1440"
            - name: PORT
              value: "{{ .Values.global.services.user.port }}"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.global.resources | nindent 12 }}
